language: node_js
node_js:
  - '12'
  - '10'
  - '8'
deploy:
  on:
    tags: true
    branch: master
  provider: npm
  email: open-source-ops@aexp.com
  api_key:
    secure: C+pu4gQu8FgUFi/mhwOjuCXc7kgb3eke0KuxqGYSaCzhrSYakZo2GDQ96eVYyGEKfco2Mp8Unm9C1KRmYcRGDChea18qcd93dRpstTEILl47jB+GiOME10YuUhYWEldZ3WlvbkDSre4sA5fS4u19974Rqqn+k7v8ZPlXzMwryBsouaAWpk09VXpn3Pe7GLhlT0Hut1V8DJ0QiFEd2LtOmXVOV02GzheObCOV5RirVfFSdwjhC+SGPBiWnmOGeD4jms6NQAetWL05sHsFhzqmHPUCKig8IsB0BVIAl/UG7RKzcxUVwMubNMbc++h6vYUN9JMWoQOm18ebZpaPzStiP5EZW2Eefma5T98O5+ryJTPLPhnwtv9+vg4PRj35cUOykDsmmaUqveqRlMrZ4SXI0eLUMCEr8NXDNotiDclBX7sD0it28CcJuCdaiB7khj8jOsMlj1HHc1q1YHo/BFPWMryMZCn8DoHfhrxQ3BoXzHENlhTtpqOBP6t35h5Wd+gbnw5h3MIYbZOVWDGEy6Ij+DPiJevOZxYD8soyARUszlJ9i2yHqxSpVZ7igJbhwWcJCmsncXbQ6BJED3n6pfxSwDZXentcmiuWdT+KMHXzPJHKO+e+WCr8MVtzCIy5AdPSnOjEYZ8VICI5YWT+HUnmjEXzPffDqvXNULWfCo56fSA=
